---
title: Saving Lives Is Not A Crime - Support Safe Consumption Sites!
baseURL: "https://savinglivesisnotacrime.com"
params:
  none: ''
disableKinds:
- RSS

params:
  description: On October 2nd, a federal judge ruled that the operation of Safehouse does not violate federal law. On October 3rd, Senator Anthony Williams released a memo stating his plans to introduce a bill that would prohibit the operation of Safe Consumption Spaces (SCS) in Pennsylvania. We need you to take action to show your support for Safehouse and urge lawmakers to oppose Sen. Williams’ plans!
  images:
  - "images/safe-consumption-now.jpg"
  title: Saving Lives Is Not A Crime - Support Safe Consumption Sites!
taxonomies:
  series:
